dist: xenial
language: cpp
os: linux
arch: ppc64le
services: docker

jobs:
  include:
    - env: CMD=rocksdbjavastaticdockerppc64le BIN=librocksdbjni-linux-ppc64le.so
    - env: CMD=rocksdbjavastaticdockerppc64lemusl BIN=librocksdbjni-linux-ppc64le-musl.so

install:
  - sudo apt-get install -y openjdk-8-jdk || exit $?
  - export PATH=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)/bin:$PATH
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)
  - echo "JAVA_HOME=${JAVA_HOME}"
  - which java && java -version
  - which javac && javac -version

script:
  - travis_wait 40 sleep 1800 & make jclean clean $CMD
#  - nice -n20 make jclean clean $CMD 2>&1
#  - travis_wait 30 make jclean clean $CMD  # The travis_wait has no effect as it still times out after 10 minutes.
#  - make jclean clean $CMD & PID=$!; while [[ -d /proc/$PID ]]; do sleep 10; echo "."; done

addons:
  artifacts:
    bucket: frocksdb-build-artifacts
    key: AKIAV5YP3MYL5BWGNIL7
    secret:
      secure: "AUrlDbya/yOCbSXNbh/7+/6RlW6ImMAgBYOA0DVDQbDeEw0ojS2CZ7bQAVahKIp66+XCWAyvk7RjuOszuuPvchA1Ss1CvzbmR96osb8xGrNqahk7yqnvCED3nKrXzVTvc56NRDBg+pxx3dF2DQFA/dSAqgkerSCnp9i4vseu3PB1SVD3A6w3ZLHnvOtWuOxJIXDTxwyKN+02KbQn5Zu2saYh3MwingPCA94pNGi9vu0eJVJxRKNccOE9dQiHSbCJGADAEhReeLR5cL6KQgJ0q4r3vE7dhbmixpqKcMGWCLLWSfu0HuvpgRgpKpfxLuwDjRBUm1iv1W1kle3GIg4bFyDvR/8U5moprX2pVXNoYUvqTM098ptaPUaM5pGCeFceZ3sOM6mMCHDcxEeLCAbJa5j9B14Y064Oxh04/groEuvm5GVHXywcm+qi59N0iFuRjyAIwtWfFPGRSxZ+2qo0IZ5KQaUBmSVuzNpBPSvDbdXYVJP5BFBemS5c+UUkyb0p9GAxAJR72GSb2KtIlKyu7mC5LTf0TPq+PeNlf7SQ60BPyUujdqb36DBxj7/bG3wZGJhIjRA3XpMXqIzxm56PmCl6UCMS84SRoA8PM5LpyQCbZAIjJzcXHVwl6BzWbcJqtYD7QDX6QmXw9R7Wy1XcbR/fjC0fVdGmi4ZLvvvmI3o="
    paths:
      - $TRAVIS_BUILD_DIR/java/target/$BIN
